apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse-system
---
# Source: clickhouse-operator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: clickhouse-operator
    chart: clickhouse-operator-0.1.0
    heritage: Tiller
    release: clickhouse-operator
  name: clickhouse-operator
  namespace: clickhouse-system

---
# Source: clickhouse-operator/templates/clusterrole.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    app: clickhouse-operator
    chart: clickhouse-operator-0.1.0
    heritage: Tiller
    release: clickhouse-operator
  name: clickhouse-operator
rules:
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - clickhouse.service.diamond.sensetime.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resourceNames:
  - default
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"

---
# Source: clickhouse-operator/templates/rolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: clickhouse-operator
    chart: clickhouse-operator-0.1.0
    heritage: Tiller
    release: clickhouse-operator
  name: clickhouse-operator
subjects:
- kind: ServiceAccount
  name: clickhouse-operator
  namespace: clickhouse-system
roleRef:
  kind: ClusterRole
  name: clickhouse-operator
  apiGroup: rbac.authorization.k8s.io

---
# Source: clickhouse-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-operator
  namespace: clickhouse-system
  labels:
    app: clickhouse-operator
    chart: clickhouse-operator-0.1.0
    heritage: Tiller
    operator: clickhouse
    release: clickhouse-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: clickhouse-operator
  template:
    metadata:
      labels:
        name: clickhouse-operator
        app: clickhouse-operator
        operator: clickhouse
        release: clickhouse-operator
    spec:
      serviceAccountName: clickhouse-operator
      securityContext:
        runAsUser: 1000
      containers:
      - name: clickhouse-operator
        image: "registry.sensetime.com/diamond/service-providers/clickhouse-operator:v0.0.1"
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
          
        env:
          - name: WATCH_NAMESPACE #如果设置为空，则监控所有namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "clickhouse-operator"
          - name: LOG_LEVEL
            value: Debug

---
# Source: clickhouse-operator/templates/service-monitor.yaml

