apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse-system
---
# Source: clickhouse-operator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: clickhouse-operator
    chart: clickhouse-operator-0.1.0
    heritage: Tiller
    release: clickhouse-operator
  name: clickhouse-operator
  namespace: clickhouse-system

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clickhouseclusters.clickhouse.service.diamond.sensetime.com
spec:
  group: clickhouse.service.diamond.sensetime.com
  names:
    kind: ClickHouseCluster
    listKind: ClickHouseClusterList
    plural: clickhouseclusters
    shortNames:
      - chc
    singular: clickhousecluster
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: ClickHouseCluster is the Schema for the clickhouseclusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClickHouseClusterSpec defines the desired state of ClickHouseCluster
          properties:
            dataCapacity:
              description: The storage capacity
              type: string
            dataStorageClass:
              description: Define StorageClass for Persistent Volume Claims in the
                local storage.
              type: string
            deletePVC:
              description: DeletePVC defines if the PVC must be deleted when the cluster
                is deleted it is false by default
              type: boolean
            image:
              description: ClickHouse Docker image
              type: string
            initImage:
              description: ClickHouse init  image
              type: string
            pod:
              description: PodPolicy defines the policy for pods owned by ClickHouse
                operator.
              properties:
                annotations:
                  additionalProperties:
                    type: string
                  description: Annotations specifies the annotations to attach to
                    headless service the ClickHouse operator creates
                  type: object
                tolerations:
                  description: Tolerations specifies the tolerations to attach to
                    the pods the ClickHouse operator creates
                  items:
                    description: The pod this Toleration is attached to tolerates
                      any taint that matches the triple <key,value,effect> using the
                      matching operator <operator>.
                    properties:
                      effect:
                        description: Effect indicates the taint effect to match. Empty
                          means match all taint effects. When specified, allowed values
                          are NoSchedule, PreferNoSchedule and NoExecute.
                        type: string
                      key:
                        description: Key is the taint key that the toleration applies
                          to. Empty means match all taint keys. If the key is empty,
                          operator must be Exists; this combination means to match
                          all values and all keys.
                        type: string
                      operator:
                        description: Operator represents a key's relationship to the
                          value. Valid operators are Exists and Equal. Defaults to
                          Equal. Exists is equivalent to wildcard for value, so that
                          a pod can tolerate all taints of a particular category.
                        type: string
                      tolerationSeconds:
                        description: TolerationSeconds represents the period of time
                          the toleration (which must be of effect NoExecute, otherwise
                          this field is ignored) tolerates the taint. By default,
                          it is not set, which means tolerate the taint forever (do
                          not evict). Zero and negative values will be treated as
                          0 (evict immediately) by the system.
                        format: int64
                        type: integer
                      value:
                        description: Value is the taint value the toleration matches
                          to. If the operator is Exists, the value should be empty,
                          otherwise just a regular string.
                        type: string
                    type: object
                  type: array
              type: object
            replicasCount:
              description: Replicas count
              format: int32
              type: integer
            shardsCount:
              description: Shards count
              format: int32
              type: integer
            zookeeper:
              description: Zookeeper config
              properties:
                identity:
                  type: string
                nodes:
                  items:
                    description: ZookeeperNode defines item of nodes section
                    properties:
                      host:
                        type: string
                      port:
                        format: int32
                        type: integer
                    required:
                      - host
                      - port
                    type: object
                  type: array
                operation_timeout_ms:
                  type: integer
                root:
                  type: string
                session_timeout_ms:
                  type: integer
              type: object
          type: object
        status:
          description: Remove subresources, cuz https://github.com/kubernetes/kubectl/issues/564
            ClickHouseClusterStatus defines the observed state of ClickHouseCluster
          properties:
            phase:
              type: string
            shardStatus: {}
          type: object
      type: object
  version: v1
  versions:
    - name: v1
      served: true
      storage: true

---
# Source: clickhouse-operator/templates/clusterrole.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    app: clickhouse-operator
    chart: clickhouse-operator-0.1.0
    heritage: Tiller
    release: clickhouse-operator
  name: clickhouse-operator
rules:
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - clickhouse.sensetime.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resourceNames:
  - default
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"

---
# Source: clickhouse-operator/templates/rolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: clickhouse-operator
    chart: clickhouse-operator-0.1.0
    heritage: Tiller
    release: clickhouse-operator
  name: clickhouse-operator
subjects:
- kind: ServiceAccount
  name: clickhouse-operator
  namespace: clickhouse-system
roleRef:
  kind: ClusterRole
  name: clickhouse-operator
  apiGroup: rbac.authorization.k8s.io

---
# Source: clickhouse-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-operator
  namespace: clickhouse-system
  labels:
    app: clickhouse-operator
    chart: clickhouse-operator-0.1.0
    heritage: Tiller
    operator: clickhouse
    release: clickhouse-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: clickhouse-operator
  template:
    metadata:
      labels:
        name: clickhouse-operator
        app: clickhouse-operator
        operator: clickhouse
        release: clickhouse-operator
    spec:
      serviceAccountName: clickhouse-operator
      securityContext:
        runAsUser: 1000
      containers:
      - name: clickhouse-operator
        image: "registry.sensetime.com/diamond/service-providers/clickhouse-operator:v0.0.1"
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
          
        env:
          - name: WATCH_NAMESPACE #如果设置为空，则监控所有namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "clickhouse-operator"
          - name: LOG_LEVEL
            value: Debug

---
# Source: clickhouse-operator/templates/service-monitor.yaml

