// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/mackwong/clickhouse-operator/pkg/apis/clickhouse/v1.ClickHouseCluster":       schema_pkg_apis_clickhouse_v1_ClickHouseCluster(ref),
		"github.com/mackwong/clickhouse-operator/pkg/apis/clickhouse/v1.ClickHouseClusterSpec":   schema_pkg_apis_clickhouse_v1_ClickHouseClusterSpec(ref),
		"github.com/mackwong/clickhouse-operator/pkg/apis/clickhouse/v1.ClickHouseClusterStatus": schema_pkg_apis_clickhouse_v1_ClickHouseClusterStatus(ref),
	}
}

func schema_pkg_apis_clickhouse_v1_ClickHouseCluster(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ClickHouseCluster is the Schema for the clickhouseclusters API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. RemoteServer may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. RemoteServer should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/mackwong/clickhouse-operator/pkg/apis/clickhouse/v1.ClickHouseClusterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/mackwong/clickhouse-operator/pkg/apis/clickhouse/v1.ClickHouseClusterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/mackwong/clickhouse-operator/pkg/apis/clickhouse/v1.ClickHouseClusterSpec", "github.com/mackwong/clickhouse-operator/pkg/apis/clickhouse/v1.ClickHouseClusterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_clickhouse_v1_ClickHouseClusterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ClickHouseClusterSpec defines the desired state of ClickHouseCluster",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_clickhouse_v1_ClickHouseClusterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ClickHouseClusterStatus defines the observed state of ClickHouseCluster",
				Type:        []string{"object"},
			},
		},
	}
}
