apiVersion: v1
description: A Helm chart for Clickhouse Kubernetes operator
name: clickhouse-operator
home: https://gitlab.bj.sensetime.com/diamond/service-providers/clickhouse
sources:
  - https://gitlab.bj.sensetime.com/diamond/service-providers/clickhouse
version: 0.1.0
appVersion: 0.1.0
icon: 
maintainers:
  - email: wangjun3@sensetime.com
    name: Wang Jun
keywords:
- operator
- clickhouse
