## Clickhouse Operator Image
##
image:
  repository: registry.sensetime.com/diamond/service-providers/clickhouse-operator
  tag: v0.5.0
  pullPolicy: Always
  imagePullSecrets:
    enabled: false
#    name:

## Prometheus-operator resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 1
    memory: 512Mi

## If true, create & deploy the CRD
##
createCustomResource: true

## If true, create & use RBAC resources
##
rbacEnable: true

## if true deploy service for metrics access
metricService: false

## If true, create & deploy the zookeeper
zookeeperConfig:
  enable: true
  replicas: 3
  nodeSelector:
    kubernetes.io/os: linux
  StoreageClass:
    enable: false
    storageClassName: local-dynamic
    storage: 2Gi

operatorNodeSelector:
  kubernetes.io/os: linux

debug:
  enabled: false

namespace: clickhouse-system
