## Clickhouse Operator Image
##
image:
  repository: registry.sensetime.com/diamond/service-providers/clickhouse-all-in-one
  tag: v1.0.0-alpha1
  pullPolicy: Always
  imagePullSecrets:
    enabled: false
#    name:

## Prometheus-operator resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 1
    memory: 512Mi

## If true, create & deploy the CRD
##
createCustomResource: true

## If true, create & use RBAC resources
##
rbacEnable: true

## if true deploy service for metrics access
metricService: true

## If true, create & deploy the zookeeper
zookeeperConfig:
  enable: false

debug:
  enabled: false

namespace: clickhouse-system
nodeSelector:
  beta.kubernetes.io/os: linux
  beta.kubernetes.io/arch: amd64

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

#tolerations:
#  - key: "node.kubernetes.io/unreachable"
#    operator: "Exists"
#    effect: "NoExecute"
tolerations: {}

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}