default_clickhouse_image: "registry.sensetime.com/diamond/service-providers/clickhouse-server:latest"
default_clickhouse_init_image: "registry.sensetime.com/diamond/service-providers/clickhouse-init:latest"
default_config:
  - ./xml/01-clickhouse-listen.xml
  - ./xml/02-clickhouse-logger.xml
default_shard_count: 1
default_replicas_count: 1
default_zookeeper:
  nodes:
    - host: zookeeper.clickhouse-system
      port: 2181
  session_timeout_ms: 30000
  operation_timeout_ms: 10000
  root: /clickhouse/tables
  identity: user:password