apiVersion: v1
description: A Helm chart for Clickhouse Kubernetes operator
name: clickhouse-operator
home: https://github.com/mackwong/clickhouse-operator
sources:
  - https://github.com/mackwong/clickhouse-operator
version: 0.1.0
appVersion: 0.1.0
icon: 
maintainers:
  - name: Mack Wang
    email: mail@mack.wang
keywords:
- operator
- clickhouse
