apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clickhouseclusters.clickhouse.sensetime.com
spec:
  group: clickhouse.sensetime.com
  names:
    kind: ClickHouseCluster
    listKind: ClickHouseClusterList
    plural: clickhouseclusters
    singular: clickhousecluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ClickHouseCluster is the Schema for the clickhouseclusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClickHouseClusterSpec defines the desired state of ClickHouseCluster
          type: object
        status:
          description: ClickHouseClusterStatus defines the observed state of ClickHouseCluster
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
