apiVersion: clickhouse.service.diamond.sensetime.com/v1
kind: ClickHouseCluster
metadata:
  name: pvd-delete
  namespace: test
spec:
  deletePVC: true
  shardsCount: 2
  replicasCount: 1
  dataStorageClass: local-dynamic
  dataCapacity: 1Gi