apiVersion: clickhouse.service.diamond.sensetime.com/v1
kind: ClickHouseCluster
metadata:
  name: simple
  namespace: test
spec:
  shardsCount: 1
  replicasCount: 2
  resources:
    requests:
      cpu: '20m'
      memory: 100Mi
    limits:
      cpu: '20m'
      memory: 100Mi
