apiVersion: clickhouse.service.diamond.sensetime.com/v1
kind: ClickHouseCluster
metadata:
  name: simple
spec:
  shardsCount: 1
  replicasCount: 2
  resources:
    requests:
      cpu: '200m'
      memory: 2Gi
    limits:
      cpu: '200m'
      memory: 2Gi
