apiVersion: clickhouse.service.diamond.sensetime.com/v1
kind: ClickHouseCluster
metadata:
  name: simple
  namespace: test
spec:
  shardsCount: 1
  replicasCount: 2
  resources:
    requests:
      cpu: '200m'
      memory: 2Gi
    limits:
      cpu: '200m'
      memory: 2Gi
  users: |
    <yandex>
        <profiles>
            <default>
                <max_memory_usage>10000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>random</load_balancing>
            </default>
            <readonly>
                <readonly>1</readonly>
            </readonly>
        </profiles>

        <users>
            <default>
                <password></password>
                <networks incl="networks" replace="replace">
                    <ip>::/0</ip>
                </networks>
                <profile>default</profile>
                <quota>default</quota>
                <databases>
                    <test>
                        <filtered_table1>
                            <filter>a = 1</filter>
                        </filtered_table1>
                        <filtered_table2>
                            <filter>a + b &lt; 1 or c - d &gt; 5</filter>
                        </filtered_table2>
                        <filtered_table3>
                            <filter>c = 1</filter>
                        </filtered_table3>
                    </test>
                </databases>
            </default>
            <sp_readonly>
                <password_sha256_hex>575c200ffb60206334abfaaafc20b2e3a410ce71ba74d510b43de6af947ed322</password_sha256_hex>
                <networks incl="networks" replace="replace">
                    <ip>::/0</ip>
                </networks>
                <profile>readonly</profile>
                <quota>default</quota>
            </sp_readonly>
        </users>

        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
    </yandex>
