apiVersion: clickhouse.service.diamond.sensetime.com/v1
kind: ClickHouseCluster
metadata:
  name: user-defined-affinity
  namespace: test
spec:
  shardsCount: 1
  replicasCount: 2
  pod:
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: team
                  operator: In
                  values:
                    - "4"
            topologyKey: kubernetes.io/hostname
