default_clickhouse_image: "registry.sensetime.com/diamond/clickhouse-server:latest"
default_clickhouse_init_image: "registry.sensetime.com/diamond/clickhouse-init:latest"
default_clickhouse_exporter_image: "registry.sensetime.com/diamond/clickhouse-exporter:latest"
default_config:
  - ./config/01-clickhouse-listen.xml
  - ./config/02-clickhouse-logger.xml
default_shard_count: 1
default_replicas_count: 1
default_data_capacity: 10Gi
default_zookeeper:
  nodes:
    - host: zookeeper.clickhouse-system
      port: 2181
  session_timeout_ms: 30000
  operation_timeout_ms: 10000
  root: /clickhouse/tables
  identity: user:password