{{- if .Values.deployClusterServiceBroker }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "version": {{ .Chart.Version }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  url: http://{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  insecureSkipTLSVerify: {{ .Values.insecure }}
{{- if .Values.authenticate}}
  authInfo:
    bearer:
      secretRef:
        namespace: "{{ .Release.Namespace }}"
        name: {{ template "fullname" . }}
{{- end }}
{{- end }}
