# Default values for the broker-skeleton
# Image to use
image:
  repository: registry.sensetime.com/diamond/service-providers/clickhouse-all-in-one
  tag: v1.0.2
  pullPolicy: Always
# ImagePullPolicy; valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: Always
authenticate: true
insecure: true
# Certificate details to use for TLS. Leave blank to not use TLS
tls:
  # base-64 encoded PEM data for the TLS certificate
  cert:
  # base-64 encoded PEM data for the private key matching the certificate
  key:
deployClusterServiceBroker: true
nodeSelector:
  beta.kubernetes.io/os: linux
  beta.kubernetes.io/arch: amd64

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##

#example:
#tolerations:
#  - key: "node.kubernetes.io/unreachable"
#    operator: "Exists"
#    effect: "NoExecute"
#    tolerationSeconds: 6000
tolerations: {}

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}