{{- if .Values.rbacEnable }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "clickhouse-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "clickhouse-operator.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "clickhouse-operator.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "clickhouse-operator.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
