apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clickhouseclusters.clickhouse.sensetime.com
  labels:
    app: {{ template "clickhouse-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: clickhouse.sensetime.com
  names:
    kind: ClickhouseCluster
    listKind: ClickhouseClusterList
    plural: clickhouseclusters
    singular: clickhousecluster
  scope: Namespaced
  version: v1
