apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "clickhouse-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "clickhouse-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    operator: clickhouse
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "clickhouse-operator.name" . }}
  template:
    metadata:
      labels:
        name: {{ template "clickhouse-operator.name" . }}
        app: {{ template "clickhouse-operator.name" . }}
        operator: clickhouse
        release: {{ .Release.Name }}
    spec:
{{- if .Values.image.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets.name }}
{{- end }}
{{- if .Values.rbacEnable }}
      serviceAccountName: {{ template "clickhouse-operator.name" . }}
{{- end }}
      securityContext:
        runAsUser: 1000
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations| indent 8}}
{{- end -}}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8}}
{{- end -}}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector| indent 8}}
{{- end }}
      containers:
      - name: {{ template "clickhouse-operator.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args:
          - operator
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: WATCH_NAMESPACE #如果设置为空，则监控所有namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DEPLOYMENT_NAME
          value: {{ template "clickhouse-operator.fullname" . }}
        - name: OPERATOR_NAME
          value: "clickhouse-operator"
{{- if .Values.debug }}
        - name: LOG_LEVEL
          value: Debug
        volumeMounts:
        - mountPath: /etc/clickhouse-operator
          name: clickhouse-operator-config
{{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: clickhouse-operator-config
        name: clickhouse-operator-config

