apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "clickhouse-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "clickhouse-operator.name" . }}
  namespace: {{ .Release.Namespace }}
